name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Runs on version tags like v1.0.0

permissions:
  contents: write  # Allow write access for creating a release

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract release notes from script
      run: |
        sed -n '/^.RELEASE NOTES/,/^#>/p' AutoTheme.ps1 | sed '1d;$d' > release-notes.txt
        echo "Extracted Release Notes:"
        cat release-notes.txt

    - name: Zip files
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        mkdir release
        cp AutoTheme.ps1 release/
        cp Config.ps1 release/
        cp Setup.ps1 release/
        cp AutoTheme.png release/
        cp LICENSE release/
        cp README.md release/
        zip -r "release-$TAG_NAME.zip" release/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: release-notes.txt
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-$TAG_NAME.zip
        asset_name: release-$TAG_NAME.zip
        asset_content_type: application/zip
